# -*- coding: utf-8 -*-
"""Text2Image_AI_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bxCZlDCj1n7c3U1Fw41LnW6tViH_DKXV
"""

!pip install diffusers transformers accelerate torch mediapy ipywidgets

import torch
from diffusers import DiffusionPipeline
import mediapy as media
import ipywidgets as widgets
from IPython.display import display
import random

pipe = DiffusionPipeline.from_pretrained(
    "digiplay/Realisian_v5",
    torch_dtype=torch.float16,
    safety_checker=None
)

pipe = pipe.to("cuda" if torch.cuda.is_available() else "cpu")

prompt_input = widgets.Text(
    description="Prompt:",
    layout=widgets.Layout(width='900px', height='40px')
)

negative_input = widgets.Text(
    description="Negative:",
    layout=widgets.Layout(width='900px', height='40px')
)


width_slider = widgets.IntSlider(value=512, min=256, max=1024, step=64, description="Width")
height_slider = widgets.IntSlider(value=768, min=256, max=1024, step=64, description="Height")

generate_btn = widgets.Button(description="Generate Image 🚀")
output = widgets.Output()

def generate_image(b):
    with output:
        output.clear_output()

        prompt = prompt_input.value
        negative_prompt = negative_input.value
        width = width_slider.value
        height = height_slider.value

        seed = random.randint(0, 1000000)

        image = pipe(
            prompt=prompt,
            width=width,
            height=height,
            negative_prompt=negative_prompt,
            generator=torch.Generator().manual_seed(seed)
        ).images[0]

        image.save("ui_generated.png")
        media.show_image(image)

        print(f"✅ Prompt: {prompt}")
        print(f"🎲 Seed: {seed}")

generate_btn.on_click(generate_image)

display(prompt_input, negative_input, width_slider, height_slider, generate_btn, output)